### ISSUE TITLE
Shame on you 

### ISSUE THREAD

**Issue by Hax4us** [adi1090x/hackapk#2]
Shame on you brother ...
You just copied whole project and published with different name 
Original Project link
https://github.com/Hax4us/Tmux-Bunch
I don't know why script kiddies do this , maybe for fame without doing hard work 

If you still think that your project is a extension of my project so can you explain how ?
Please don't spoil open source projects glamour and other hard works

**Comment by adi1090x** [comment]
If you're arguing about copying your work, then you don't know what the "open source" exactly stands for. No more argument needed. 
And FYI, "Open Source - denoting software for which the original source code is made freely available and may be redistributed and modified."
That's what i did, and yes this tool is an extension of your program, because it's more organized and  well written.
And now if you're taking about fame, I'm not promoting it like you do everywhere on your CMS powered website and YouTube channels.
And I've mentioned your program in this repo, clearly showsing what I've done. If on people what they choose. (BTW, i loved your program so much that i invested my time on that to make that more awesome)
Is that it, fame hunter?
Shame On You BTW... Read the fuckin rules of open source community.

**Comment by Hax4us** [comment]
changing the name of author is "not extension" in any way.
